import { useEffect, useMemo, useState } from "react";
import { useParams } from "wouter";
import { ArrowRight, BarChart3, CheckCircle2, Globe2, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteFooter } from "@/components/site-footer";

type Poll={slug:string;title:string;description?:string;timezone:string;durationMinutes:number;options:string[];status:string;counts:Record<string,number>;responseCount:number;finalStart?:string};
function localZone(){return Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"}
function show(iso:string,timeZone:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(iso))}

export default function PublicPoll(){
 const {slug}=useParams<{slug:string}>();const visitorZone=useMemo(localZone,[]);const[poll,setPoll]=useState<Poll|null>(null);const[selected,setSelected]=useState<string[]>([]);const[name,setName]=useState("");const[email,setEmail]=useState("");const[loading,setLoading]=useState(true);const[done,setDone]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/polls/${encodeURIComponent(slug)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setPoll(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[slug]);
 async function submit(){setLoading(true);setError("");try{const r=await fetch(`/api/polls/${encodeURIComponent(slug)}/responses`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participantName:name,participantEmail:email,participantTimezone:visitorZone,selections:selected})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDone(true)}catch(e){setError(e instanceof Error?e.message:"Could not submit")}finally{setLoading(false)}}
 if(loading&&!poll)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin text-primary"/></div>;
 if(!poll)return <div className="min-h-screen grid place-items-center"><p>{error||"Poll not found"}</p></div>;
 return <div className="min-h-screen bg-[#f8f9ff]"><header className="max-w-3xl mx-auto p-5"><a href="/"><img src="/logo-transparent.png" alt="MeetMind" className="w-40"/></a></header><main className="max-w-3xl mx-auto px-5 pb-16"><div className="bg-white rounded-3xl border shadow-sm p-6 sm:p-9"><div className="w-12 h-12 rounded-2xl bg-primary/10 grid place-items-center"><BarChart3 className="text-primary"/></div><h1 className="text-3xl font-bold mt-5">{poll.title}</h1>{poll.description&&<p className="text-muted-foreground mt-2">{poll.description}</p>}<p className="flex items-center gap-2 text-sm text-muted-foreground mt-5"><Globe2 className="w-4 h-4"/>Times shown in {visitorZone}; organizer timezone is {poll.timezone}.</p>
 {poll.status!=="open"?<div className="mt-8 rounded-2xl bg-emerald-50 border border-emerald-200 p-6"><CheckCircle2 className="text-emerald-600"/><h2 className="font-bold text-xl mt-3">Meeting time confirmed</h2><p className="mt-1">{poll.finalStart?show(poll.finalStart,visitorZone):"The organizer has finalized this poll."}</p></div>:done?<div className="mt-8 text-center py-8"><CheckCircle2 className="w-14 h-14 text-emerald-500 mx-auto"/><h2 className="font-bold text-2xl mt-4">Response recorded</h2><p className="text-muted-foreground mt-2">The organizer can now see which times work for you.</p><div className="mt-7 rounded-2xl bg-slate-950 text-white p-6"><h3 className="font-bold text-xl">Create your own booking page</h3><p className="text-slate-300 text-sm mt-2">Use MeetMind for instant bookings, group polls, and a private smart calendar.</p><a href="/sign-up"><Button className="mt-5">Create free account <ArrowRight className="ml-2 w-4 h-4"/></Button></a></div></div>:<><div className="mt-8 space-y-3">{poll.options.map(option=><label key={option} className={`block rounded-2xl border p-4 cursor-pointer transition ${selected.includes(option)?"border-primary bg-primary/5":"hover:border-primary/30"}`}><div className="flex gap-3"><input type="checkbox" checked={selected.includes(option)} onChange={e=>setSelected(items=>e.target.checked?[...items,option]:items.filter(i=>i!==option))}/><div><p className="font-bold">{show(option,visitorZone)}</p><p className="text-sm text-muted-foreground">{show(option,poll.timezone)} organizer time • {poll.counts[option]||0} available</p></div></div></label>)}</div><div className="grid sm:grid-cols-2 gap-4 mt-7"><label className="space-y-2"><span className="font-semibold text-sm">Your name</span><Input value={name} onChange={e=>setName(e.target.value)}/></label><label className="space-y-2"><span className="font-semibold text-sm">Email (optional)</span><Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div>{error&&<p className="text-destructive mt-3">{error}</p>}<Button size="lg" className="mt-6 rounded-xl" onClick={submit} disabled={!name||!selected.length||loading}>Submit availability</Button></>}
 </div></main><SiteFooter /></div>
}
